### ISSUE TITLE
v3.0 Proposal

### ISSUE THREAD

**Issue by pierrejacques** [pierrejacques/IPA.js#14]
new:
- IPA.Order, // 有序遍历的数组
- IPA.Integer,
- IPA.NonNeg, // >=0
- IPA.Positive, // >0
- IPA.Finite, // !NaN && !Infinite
- IPA.Range(min, max),
- IPA.Dict(subtype),
- IPA.or,
- IPA.and, // e.g. IPA.and(IPA.NonNeg, IPA.Integer)
- IPA.setEnv,
- Vue.use(IPA), // maybe a separate 'vue-ipa' // 没太大必要
- Vue.component.schema
- [null, '<num'],
- [null, '<=num'],
- [null, '>num'],
- [null, '>=num'],
- [null, '<3'],
- [null, '<=3'],
- [null, '>3'],
- [null, '>=3'],

README.md: 
- template => schema

**Comment by siholic1129** [comment]
range，or，order => each，setEnv

**Comment by pierrejacques** [comment]
- IPA.Required

**Comment by pierrejacques** [comment]
- [ ] Enum

**Comment by pierrejacques** [comment]
guarantee的时候类应该近点靠，比如1，guarantee到Boolean应为true
