### ISSUE TITLE
报错机制

### ISSUE THREAD

**Issue by pierrejacques** [pierrejacques/IPA.js#20]
### 概述

在check或者guarantee方法识别到错误的时候，应该通过一种数据格式，详尽地报告错误所在，并通过某个出口，发出这个错误报告

### 报错的位置

以我目前的理解有三个报错的位置，在设计中亦可以考虑这三个位置都可以报出错误：

- 全局：在IPA的全局实例中配置报错钩子
- 实例：在IPA实例中配置报错钩子（我本人比较推荐）
- 方法：在调用实例方法的时候设置报错钩子

### 报错的方式

- 链式调用（不一定异步）：通过`then().catch()`的方式进行IPA报错，主流程处理，和业务相关的错误处理
- 在需要的位置挂钩子（没想好怎么挂到特定方法上）：如`instance.on('error', callback)`

欢迎补充讨论

**Comment by siholic1129** [comment]
全局定义默认的报错钩子函数的行为，在实例维度可以对其进行覆盖。

**Comment by pierrejacques** [comment]
可以给用户提供一种串行的可能性，把钩子函数写成`(errorInfo, next) => {}`的形式，从而允许实例的钩子函数挂在全局的前面

**Comment by pierrejacques** [comment]
每个方法层面的精细话报错的场景是值得考虑的。应用在需要针对不同的错误进行精细的情形下，但是我预估场景不大。

这种报错方式采用
``` js
instance.method( ).then( ).catch((errInfo, next) => {})
```
的方式来报错。

虽然场景不大，但还是应该为用户提供这种精细化处理的途径。

**Comment by pierrejacques** [comment]
onError已经实现，then catch方式的使用场景存疑。
